# Permalinks
permalink:           pretty

# Setup
title:               Bader Alafnan
tagline:             Data Science and Machine Learning Blogs
url:                 http://alafnan.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bader Alafnan
  url:               https://twitter.com/BaderAlafnan1
  email:             Bader.Alafnan@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/alafnan

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About me: '/about me'
  Projects lists: '/archive'
